### ISSUE TITLE
There is something wrong in build step

### ISSUE THREAD

**Issue by Rikka-Sei** [tommego/qspine#1]
When I use Qt 5.14.2 and MinGw 32-bit to build this project , build kits prevented me.
![image](https://user-images.githubusercontent.com/36284614/101987703-ca4f7080-3cd0-11eb-8678-b272818670dd.png)

So,can you offer me your develop-environment‘s config,I think it will helpful.

Thank you.

**Comment by Rikka-Sei** [comment]
Sorry , my network is so slow that I press F5 double.

**Comment by Rikka-Sei** [comment]
Please help me delete this issues if it is possible.

**Comment by tommego** [comment]
Sorry! I'm very busy to browse github recently and now read some issues here, is there any problem that needs help?
