### ISSUE TITLE
Something wrong on build step

### ISSUE THREAD

**Issue by Rikka-Sei** [tommego/qspine#2]
When I use Qt 5.14.2 and MinGw 32-bit to build this project , build kits prevented me.
![image](https://user-images.githubusercontent.com/36284614/101987703-ca4f7080-3cd0-11eb-8678-b272818670dd.png)

So,can you offer me your develop-environment‘s config? I think it will helpful.

Thank you.

**Comment by tommego** [comment]
gl_pointsize那行代码注释掉，有些平台没这个接口。
